services:
  - type: web
    name: schoolbattle
    env: node
    buildCommand: npm install && cd server && npm install
    startCommand: node index.js
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
